# Generated by Django 2.1.2 on 2018-11-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dt', models.DateTimeField(blank=True, db_column='from', null=True)),
                ('to_dt', models.DateTimeField(blank=True, null=True)),
                ('renewable', models.BooleanField(blank=True, null=True)),
                ('amount', models.ForeignKey(blank=True, db_column='amount', null=True, on_delete=django.db.models.deletion.PROTECT, to='outletapp.Amount')),
            ],
        ),
        migrations.CreateModel(
            name='EstimatedSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('code', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('is_retail', models.BooleanField(blank=True, null=True)),
                ('estimated_sales', models.ForeignKey(blank=True, db_column='estimated', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outletapp.EstimatedSales')),
                ('medias', models.ManyToManyField(blank=True, to='outletapp.Media')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('location_dt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallunit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WallUnitBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WallUnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='wallunit',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outletapp.WallUnitBrand'),
        ),
        migrations.AddField(
            model_name='wallunit',
            name='medias',
            field=models.ManyToManyField(related_name='medias', to='outletapp.Media'),
        ),
        migrations.AddField(
            model_name='wallunit',
            name='outlet',
            field=models.ForeignKey(blank=True, db_column='outlet', null=True, on_delete=django.db.models.deletion.CASCADE, to='outletapp.Outlet'),
        ),
        migrations.AddField(
            model_name='wallunit',
            name='wall_unit_type',
            field=models.ForeignKey(blank=True, db_column='type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outletapp.WallUnitType'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='size',
            field=models.ForeignKey(blank=True, db_column='size', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='outletapp.Size'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outletapp.Outlet'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='payment', null=True, on_delete=django.db.models.deletion.PROTECT, to='outletapp.PaymentType'),
        ),
        migrations.AddField(
            model_name='contract',
            name='remark',
            field=models.ForeignKey(blank=True, db_column='remark', null=True, on_delete=django.db.models.deletion.PROTECT, to='outletapp.Remark'),
        ),
    ]
