# Generated by Django 2.1.2 on 2018-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='local_password',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
