# Generated by Django 2.1.2 on 2018-11-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outletapp', '0002_userprofile_local_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
